apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-csharp-webapp
spec:
  selector:
    matchLabels:
      app: sample-csharp-webapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sample-csharp-webapp
    spec:
      containers:
      - name: sample-csharp-webapp
        image: venki231/csharp:0.0.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
